name: tests

on:
  push:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run tests
      uses: koenhagen/measure-energy-action@v0.27
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test main_test.go main.go
        count: 20